services:
  _defaults:
    public: true
    autowire: true

  HeimrichHannot\EntityImportBundle\DataContainer\EntityImportContainer: ~
  HeimrichHannot\EntityImportBundle\DataContainer\EntityImportConfigContainer: ~