services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  HeimrichHannot\EntityImportBundle\:
    resource: '../../{Command,Controller,DataContainer,EventListener}/*'

  HeimrichHannot\EntityImportBundle\Importer\ImporterFactory: ~
  HeimrichHannot\EntityImportBundle\Source\SourceFactory: ~
  HeimrichHannot\EntityImportBundle\Util\EntityImportUtil: ~
