services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  HeimrichHannot\EntityImportBundle\:
    resource: '../../{Command,Controller,DataContainer,EventListener,Util}/*'

  HeimrichHannot\EntityImportBundle\Importer\ImporterFactory: ~
  HeimrichHannot\EntityImportBundle\Source\SourceFactory: ~
