services:
  _defaults:
    autowire: true

  HeimrichHannot\EntityImportBundle\Importer\ImporterFactory: ~
  HeimrichHannot\EntityImportBundle\Source\SourceFactory: ~
  HeimrichHannot\EntityImportBundle\Util\EntityImportUtil: ~
